# Generated by Django 3.0.7 on 2020-08-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200811_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='upload',
            new_name='resume',
        ),
    ]
