# Generated by Django 3.0.7 on 2020-08-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200811_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='files')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(max_length=350, null=True),
        ),
    ]
