# Generated by Django 3.0.7 on 2020-08-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200814_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vediofile', models.FileField(null=True, upload_to='files')),
            ],
        ),
    ]
