# Generated by Django 3.0.7 on 2020-08-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_uploadvedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvedio',
            name='vediofile',
            field=models.FileField(null=True, upload_to='files', verbose_name=''),
        ),
    ]
