# Generated by Django 3.2.4 on 2021-06-05 19:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.FileField(blank=True, null=True, upload_to='gallery', verbose_name='Add Photos to Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('post_image', models.FileField(blank=True, null=True, upload_to='posts', verbose_name='Add Photos to Article')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, null=True)),
                ('last_name', models.CharField(max_length=32, null=True)),
                ('headline', models.CharField(max_length=100, null=True)),
                ('bio', models.TextField(max_length=350, null=True)),
                ('linkedin', models.CharField(max_length=250, null=True)),
                ('github', models.CharField(max_length=250, null=True)),
                ('picture', models.ImageField(null=True, upload_to='profile_pics')),
                ('resume', models.FileField(null=True, upload_to='docs')),
                ('skills', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title :')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=400)),
                ('pub_link', models.CharField(max_length=1000)),
                ('absract', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title :')),
                ('collaborators', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug :')),
                ('thumbnail', models.ImageField(upload_to='content/blog/thumbnail/', verbose_name='Thumbnail :')),
                ('publish', models.BooleanField(default=True, help_text='Will this post be published?', verbose_name='Publish :')),
                ('completed', models.BooleanField(default=True, help_text='is this post completed?', verbose_name='Completed :')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ManyToManyField(to='research_site.ProjectCategory')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
