# Generated by Django 3.2.4 on 2021-06-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='absract',
            new_name='abstract',
        ),
    ]
