# Generated by Django 3.2.4 on 2021-06-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.FileField(blank=True, null=True, upload_to='posts', verbose_name='Add Photos to Article'),
        ),
    ]
