# Generated by Django 3.2.4 on 2021-06-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0002_auto_20210605_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(),
        ),
    ]
