# Generated by Django 3.2.4 on 2021-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.FileField(blank=True, null=True, upload_to='projects', verbose_name='Add Photos to Article'),
        ),
    ]
