# Generated by Django 3.2.4 on 2021-06-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0004_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False, help_text='is this post completed?', verbose_name='Completed :'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.FileField(blank=True, null=True, upload_to='projects', verbose_name='Add Photos to Project'),
        ),
    ]
