# Generated by Django 3.2.4 on 2021-06-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
