# Generated by Django 3.2.4 on 2021-06-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
