# Generated by Django 3.2.4 on 2021-06-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0008_auto_20210615_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='proj_cat_image',
            field=models.FileField(blank=True, null=True, upload_to='proj_cat_images', verbose_name='Add Photos to Project-Category'),
        ),
    ]
