# Generated by Django 3.2.4 on 2021-08-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0011_project_advisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='advisor',
            new_name='adviser',
        ),
    ]
