# Generated by Django 3.2.4 on 2021-10-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0016_rename_category_project_areaofresearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='areaOfResearch',
            new_name='areaofresearch',
        ),
    ]
