# Generated by Django 3.2.4 on 2021-10-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0017_rename_areaofresearch_project_areaofresearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='areaofresearch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_site.projectcategory', verbose_name='Areas'),
        ),
    ]
