# Generated by Django 3.2.4 on 2021-10-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0019_alter_project_areaofresearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='areaofresearch',
            new_name='category',
        ),
    ]
