# Generated by Django 3.2.4 on 2021-10-31 20:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0020_rename_areaofresearch_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
