# Generated by Django 3.2.4 on 2021-10-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0021_auto_20211031_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='adviser',
            field=models.CharField(blank=True, help_text='E.g Prof.Tarimo', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False, help_text='is this project completed?', verbose_name='Completed :'),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish',
            field=models.BooleanField(default=True, help_text='Do you want to post this project?', verbose_name='Publish :'),
        ),
    ]
