# Generated by Django 3.2.4 on 2021-10-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0025_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(verbose_name='Creation Date'),
        ),
    ]
