# Generated by Django 3.2.4 on 2021-10-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0026_alter_publication_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='pub_link',
            new_name='publication_link',
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(verbose_name='Creation Date: YYYY-MM-DD'),
        ),
    ]
