# Generated by Django 3.2.4 on 2021-10-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0029_auto_20211031_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.FileField(null=True, upload_to='gallery', verbose_name='Add Photos to Gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(null=True, upload_to='posts', verbose_name='Add Photos to Article'),
        ),
        migrations.AlterField(
            model_name='project',
            name='adviser',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.FileField(null=True, upload_to='projects', verbose_name='Add Photos to Project'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='proj_cat_image',
            field=models.FileField(null=True, upload_to='proj_cat_imageßs', verbose_name='Add Photos to Project-Category'),
        ),
    ]
