# Generated by Django 3.2.4 on 2021-10-31 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_site', '0030_auto_20211031_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_site.projectcategory', verbose_name='Research Area'),
        ),
    ]
